import './globals.css';

import type { Metadata } from 'next';
import { Anton, Inter_Tight } from 'next/font/google';

import { ToastProvider } from '@/components/ui/toast';
import { UserProvider } from '@/context/user-provider';
import { QueryProvider } from '@/providers/query-provider';

const interTight = Inter_Tight({
  variable: '--font-inter-tight',
  subsets: ['latin'],
  weight: ['400', '600'],
});

const anton = Anton({
  variable: '--font-anton',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interTight.variable} ${anton.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-primary">
        <ToastProvider>
          <QueryProvider>
            <UserProvider>{children}</UserProvider>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
